### PR TITLE
Add new MDC and UPS operator bundles

### PR DESCRIPTION
**Pull request by grdryn**
I don't really know what I'm doing here, or what I need to do apart
from opening this PR. Please let me know if there's anything I need to
do apart from this!

### CODE REVIEW

**Comment by grdryn** [comment]
Bump :smile_cat: 

bump

**Comment by philbrookes** [comment]
Can we get a coinciding bump to the operator version in the integreatly-operator, here please: 
https://github.com/integr8ly/integreatly-operator/blob/master/pkg/apis/integreatly/v1alpha1/installation_types.go#L77

**Comment by philbrookes** [comment]
the version of UPS in the makefile needs to be bumped too.

**Comment by grdryn** [comment]
> the version of UPS in the makefile needs to be bumped too.

Done. :+1:

**Pull request merged**
